version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

workflows:
  workflow:
    jobs:
      - build